//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DOANDL
    {
        static QuanlyTourEntities1 db = new QuanlyTourEntities1();
        public string MaDOANDL { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }
        public string MaTour { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TOURDULICH TOURDULICH { get; set; }
        public static List<DOANDL> LoadDataDoanDL()
        {
           //  using (var db = new QuanlyTourEntities1())
            {
                var result = db.DOANDLs.ToList();
                return result;
            }
        }
    }
}
