//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DOANDLs = new HashSet<DOANDL>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> KH_NgaySinh { get; set; }
        public string KH_DiaChi { get; set; }
        public Nullable<int> KH_SoDienThoai { get; set; }
        public string KH_GioiTinh { get; set; }
        public string KH_email { get; set; }
        public string KH_CMND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOANDL> DOANDLs { get; set; }
    }
}
