//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Forms;
    

    public partial class TOURDULICH
    {
        static QuanlyTourEntities1 db = new QuanlyTourEntities1();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOURDULICH()
        {
            this.CHITIETs = new HashSet<CHITIET>();
            this.DOANDLs = new HashSet<DOANDL>();
        }
    
        public string MaTour { get; set; }
        public string TenTour { get; set; }
        public string DacDiem { get; set; }
        public string IDGiaTour { get; set; }
        public string MaDOANDL { get; set; }
        public string MaLoaiHinh { get; set; }
        public string MaDiaDiem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET> CHITIETs { get; set; }
        public virtual DIADIEM DIADIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOANDL> DOANDLs { get; set; }
        public virtual GIATOUR GIATOUR { get; set; }
        public virtual LOAIHINHDULICH LOAIHINHDULICH { get; set; }
    }
}
